USE T_Opflix;

CREATE TABLE Usuarios(
	IdUsuario INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL
	,Email VARCHAR(200) NOT NULL
	,CPF INT NOT NULL
	,Permissao VARCHAR(7) NOT NULL
);
CREATE TABLE FS(
	IdFS INT PRIMARY KEY IDENTITY
	,Qual VARCHAR(50)
);
CREATE TABLE Plataforma (
	IdPlataforma INT PRIMARY KEY IDENTITY NOT NULL
	,Nome VARCHAR(200) NOT NULL
);
CREATE TABLE Categorias (
	IdCategoria INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(100) NOT NULL
);
CREATE TABLE Conteudo(
		IdConteudo INT PRIMARY KEY IDENTITY
		,Titulo VARCHAR(255) NOT NULL
		,Sinopse VARCHAR(255) NOT NULL
		,DLanc SMALLDATETIME NOT NULL
		,Duracao TIME NOT NULL
		,IdCategoria INT FOREIGN KEY REFERENCES Categorias (IdCategoria)
		,IdFS  INT FOREIGN KEY REFERENCES FS (IdFS)
		,IdPlataforma INT FOREIGN KEY REFERENCES Plataforma (IdPlataforma)
		,IdUsuario INT FOREIGN KEY REFERENCES Usuarios (IdUsuario)
);